export const GET_POST_REQUEST = 'GET_POST_REQUEST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const RESET_ACTIVITIES = 'RESET_ACTIVITIES';
export const RESET_POST_LOAD = 'RESET_POST_LOAD';
export const RESET_FALSE_POST_LOAD = 'RESET_FALSE_POST_LOAD';
export const UPDATE_PATH = 'UPDATE_PATH';
